try all

diff --git a/.github/workflows/build-test-lin.yml b/.github/workflows/build-test-lin.yml
--- a/.github/workflows/build-test-lin.yml
+++ b/.github/workflows/build-test-lin.yml
@@ -77,7 +77,7 @@ jobs:
   build:
     env:
       TEST_EXE: build/aprapipesut
-      LD_LIB_PATH: './thirdparty/gst-build/gst-build-1.16/outInstall/lib/x86_64-linux-gnu:/usr/local/cuda-10.2/compat/:/usr/local/cuda/lib64:${LD_LIBRARY_PATH-}'
+      LD_LIB_PATH: './thirdparty/gst-build/gst-build-1.16/outInstall/lib/x86_64-linux-gnu:./thirdparty/Video_Codec_SDK_10.0.26/Lib/linux/stubs/x86_64:/usr/local/cuda-10.2/compat/:/usr/local/cuda/lib64:${LD_LIBRARY_PATH-}'
       CMAKE_TC_FILE: '../vcpkg/scripts/buildsystems/vcpkg.cmake' # Note: naming this variable as CMAKE_TOOLCHAIN_FILE can cause havoc!!!
     runs-on: ${{ inputs.runner }}
     steps:
@@ -85,7 +85,7 @@ jobs:
       run: |
         ${{ inputs.prep-cmd }} 
         apt purge cmake || true
-        pip3 install cmake --upgrade || true
+        pip3 install cmake --upgrade || echo 'did not update cmake'
         ${{ inputs.prep-check-cmd }} 
     
     - name: Check builder for CUDA
@@ -149,18 +149,12 @@ jobs:
     - name: Build Gstreamer On Linux_x64 when it is not cached
       if: ${{ inputs.is-build-gst && steps.cache-all.outputs.cache-hit != 'true'}}
       working-directory: ${{github.workspace}}/thirdparty
-      run: |
-        (dos2unix ./build_gstreamer.sh) || true
-        chmod a+x ./build_gstreamer.sh
-        ./build_gstreamer.sh
+      run: sh build_gstreamer.sh
     
     - name: Build libmp4 when it is not cached
       if: ${{ steps.cache-all.outputs.cache-hit != 'true' }}
       working-directory: ${{github.workspace}}/thirdparty/libmp4
-      run: |
-        (dos2unix ./build.cmd) || true
-        chmod a+x ./build.cmd
-        ./build.cmd
+      run: build.cmd
     
     - name: Make build folder
       run: mkdir -p build
@@ -180,14 +174,16 @@ jobs:
       env:
         LD_LIBRARY_PATH: ${{env.LD_LIB_PATH}}
       if: ${{!inputs.is-prep-phase}}
-      run: ${{env.TEST_EXE}} --list_content > tests.txt
+      run: |
+        ldd ${{env.TEST_EXE}}
+        ${{env.TEST_EXE}} --list_content > tests.txt
       timeout-minutes: 1
 
     - name: Run Tests
       if: ${{!inputs.is-prep-phase && !inputs.skip-test}}
       env:
         LD_LIBRARY_PATH: ${{env.LD_LIB_PATH}}
-      run: ${{env.TEST_EXE}} --log_format=JUNIT --log_sink=CI_test_result_${{inputs.flav}}.xml -p -l all || true
+      run: ${{env.TEST_EXE}} --log_format=JUNIT --log_sink=CI_test_result_${{inputs.flav}}.xml -p -l all || echo 'test execution returned error'
       timeout-minutes: ${{ inputs.nTestTimeoutMins}}
     
     - name: Upload Test Results
diff --git a/.github/workflows/build-test-win.yml b/.github/workflows/build-test-win.yml
--- a/.github/workflows/build-test-win.yml
+++ b/.github/workflows/build-test-win.yml
@@ -4,13 +4,11 @@ on:
       runner:
         type: string
         description: 'runner where this job will run'
-        default: 'windows-2019'
-        required: false
+        required: true
       flav: 
         type: string
-        description: 'flavour of the build: windows/linux_x64/linux_arm64'
-        default: 'Windows'
-        required: false
+        description: 'flavour of the build: Windows/linux_x64/linux_arm64'
+        required: true
       buildConf:
         type: string
         description: 'build configuration e.g. Release/Debug etc.'
@@ -19,8 +17,7 @@ on:
       is-selfhosted: 
         type: boolean
         description: 'self hosted runners do not need to use cache'
-        default: false
-        required: false
+        required: true
       skip-test: 
         type: boolean
         description: 'should test steps be skipped'
@@ -29,13 +26,18 @@ on:
       cuda: 
         type: string
         description: 'ON/OFF based on this runner support cuda'
-        default: 'OFF'
-        required: false
+        required: true
       prep-cmd:
         type: string
         description: 'commands required to be run on a builder to prep it for build'
         default: 'pip3 install ninja && pip3 install meson && choco feature enable -n allowEmptyChecksums && choco install pkgconfiglite'
         required: false
+      prep-check-cmd:
+        type: string
+        description: 'command to check if the builder is ready'
+        default: 'cmake --version ; ninja --version ; git --version; pwsh --version'
+        #pwsh is required on self hosted runners: see here: https://learn.microsoft.com/en-us/powershell/scripting/install/install-other-linux?view=powershell-7.2#installation-using-a-binary-archive-file     
+        required: false                
       bootstrap-cmd:
         type: string
         description: 'commands required to boot strap builder after code checkout'
@@ -49,7 +51,7 @@ on:
       is-build-gst:
         type: boolean
         description: 'should we build GStreamer? we dont build on windows and ARM_Linux.'
-        default: false
+        default: true
         required: false
       cache-path:
         type: string
@@ -64,7 +66,7 @@ on:
       nProc:
         type: number
         description: 'number of threads to be used by cmake/make'
-        default: 3
+        default: 6
         required: false
       nTestTimeoutMins:
         type: number
@@ -80,7 +82,16 @@ jobs:
     runs-on: ${{ inputs.runner }}
     steps:
     - name: Prepare builder
-      run: ${{ inputs.prep-cmd }} 
+      run: |
+      ${{ inputs.prep-cmd }} 
+      pip3 install cmake --upgrade || echo 'did not update cmake'
+      ${{ inputs.prep-check-cmd }} 
+    
+    - name: Check builder for CUDA
+      if: ${{ contains(inputs.cuda,'ON')}} 
+      run: |
+        (nvcc --version) || echo 'please install cuda'
+        Get-Item 'c:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.7\include\cudnn.h' || echo 'install cudnn as described in the readme.md'
     
     - name: Cleanup workspace on self hosted runners
       if: inputs.is-selfhosted
@@ -124,7 +135,6 @@ jobs:
       continue-on-error: true
 
     - name: Cache dependencies for fast cloud build
-      if: ${{ !inputs.is-selfhosted }}
       id: cache-all
       uses: actions/cache@v2
       with:
@@ -132,7 +142,7 @@ jobs:
             ${{ inputs.cache-path }}
             ${{ github.workspace }}/thirdparty/gst-build/gst-build-1.16/outInstall/
             ${{ github.workspace }}/thirdparty/libmp4/build
-          key:  ${{ inputs.flav }}-${{ hashFiles( 'base/vcpkg.json', 'vcpkg/baseline.json', 'submodule_ver.txt') }}
+          key:  ${{ inputs.flav }}-3-${{ hashFiles( 'base/vcpkg.json', 'vcpkg/baseline.json', 'submodule_ver.txt') }}
           restore-keys: ${{ inputs.flav }}-
 
     - name: Build Gstreamer On Linux_x64 when it is not cached
@@ -143,7 +153,7 @@ jobs:
     - name: Build libmp4 when it is not cached
       if: ${{ steps.cache-all.outputs.cache-hit != 'true' }}
       working-directory: ${{github.workspace}}/thirdparty/libmp4
-      run: ./build.cmd
+      run: build.cmd
 
     - name: Make build folder
       run: mkdir -p build
@@ -170,7 +180,7 @@ jobs:
       if: ${{!inputs.is-prep-phase && !inputs.skip-test}}
       env:
         LD_LIBRARY_PATH: ${{env.LD_LIB_PATH}}
-      run: ${{env.TEST_EXE}} --log_format=JUNIT --log_sink=CI_test_result_${{inputs.flav}}.xml -p -l all
+      run: ${{env.TEST_EXE}} --log_format=JUNIT --log_sink=CI_test_result_${{inputs.flav}}.xml -p -l all || echo 'test execution returned error'
       timeout-minutes: ${{ inputs.nTestTimeoutMins}}
     
     - name: Upload Test Results
diff --git a/.github/workflows/build-test-wsl.yml b/.github/workflows/build-test-wsl.yml
--- a/.github/workflows/build-test-wsl.yml
+++ b/.github/workflows/build-test-wsl.yml
@@ -77,7 +77,7 @@ jobs:
   build:
     env:
       TEST_EXE: build/aprapipesut
-      LD_LIB_PATH: './thirdparty/gst-build/gst-build-1.16/outInstall/lib/x86_64-linux-gnu:/usr/local/cuda-10.2/compat/:/usr/local/cuda/lib64:${LD_LIBRARY_PATH-}'
+      LD_LIB_PATH: './thirdparty/gst-build/gst-build-1.16/outInstall/lib/x86_64-linux-gnu:./thirdparty/Video_Codec_SDK_10.0.26/Lib/linux/stubs/x86_64:/usr/local/cuda-10.2/compat/:/usr/local/cuda/lib64:${LD_LIBRARY_PATH-}'
       CMAKE_TC_FILE: '../vcpkg/scripts/buildsystems/vcpkg.cmake' # Note: naming this variable as CMAKE_TOOLCHAIN_FILE can cause havoc!!!
     runs-on: ${{ inputs.runner }}
     steps:
@@ -89,7 +89,7 @@ jobs:
       run: |
         ${{ inputs.prep-cmd }} 
         apt purge cmake || true
-        pip3 install cmake --upgrade || true
+        pip3 install cmake --upgrade || echo 'did not update cmake'
         ${{ inputs.prep-check-cmd }} 
       shell: wsl-bash {0}
     
@@ -153,22 +153,25 @@ jobs:
           key:  ${{ inputs.flav }}-3-${{ hashFiles( 'base/vcpkg.json', 'vcpkg/baseline.json', 'submodule_ver.txt') }}
           restore-keys: ${{ inputs.flav }}-
 
-    - name: Build Gstreamer On Linux_x64 when it is not cached
-      if: ${{ inputs.is-build-gst && steps.cache-all.outputs.cache-hit != 'true'}}
+    - name: On WSL prep the thirdparty build scripts
       working-directory: ${{github.workspace}}/thirdparty
       run: |
         (dos2unix ./build_gstreamer.sh) || true
         chmod a+x ./build_gstreamer.sh
-        ./build_gstreamer.sh
+        (dos2unix libmp4/build.cmd) || true
+        chmod a+x libmp4/build.cmd
+      shell: wsl-bash {0}
+
+    - name: Build Gstreamer On Linux_x64 when it is not cached
+      if: ${{ inputs.is-build-gst && steps.cache-all.outputs.cache-hit != 'true'}}
+      working-directory: ${{github.workspace}}/thirdparty
+      run: sh build_gstreamer.sh
       shell: wsl-bash {0}
     
     - name: Build libmp4 when it is not cached
       if: ${{ steps.cache-all.outputs.cache-hit != 'true' }}
       working-directory: ${{github.workspace}}/thirdparty/libmp4
-      run: |
-        (dos2unix ./build.cmd) || true
-        chmod a+x ./build.cmd
-        ./build.cmd
+      run: build.cmd
       shell: wsl-bash {0}
     
     - name: Make build folder
@@ -191,7 +194,9 @@ jobs:
       env:
         LD_LIBRARY_PATH: ${{env.LD_LIB_PATH}}
       if: ${{!inputs.is-prep-phase}}
-      run: ${{env.TEST_EXE}} --list_content > tests.txt
+      run: |
+        ldd ${{env.TEST_EXE}}
+        ${{env.TEST_EXE}} --list_content > tests.txt
       timeout-minutes: 1
       shell: wsl-bash {0}
       
@@ -199,7 +204,7 @@ jobs:
       if: ${{!inputs.is-prep-phase && !inputs.skip-test}}
       env:
         LD_LIBRARY_PATH: ${{env.LD_LIB_PATH}}
-      run: ${{env.TEST_EXE}} --log_format=JUNIT --log_sink=CI_test_result_${{inputs.flav}}.xml -p -l all || true
+      run: ${{env.TEST_EXE}} --log_format=JUNIT --log_sink=CI_test_result_${{inputs.flav}}.xml -p -l all || echo 'test execution returned error'
       timeout-minutes: ${{ inputs.nTestTimeoutMins}}
       shell: wsl-bash {0}
     
