fixes

diff --git a/.github/workflows/build-test-lin-container.yml b/.github/workflows/build-test-lin-container.yml
--- a/.github/workflows/build-test-lin-container.yml
+++ b/.github/workflows/build-test-lin-container.yml
@@ -159,7 +159,7 @@ jobs:
       if: ${{ steps.cache-all.outputs.cache-hit != 'true' }}
       working-directory: ${{github.workspace}}/thirdparty/libmp4
       run: ./build.cmd
-
+    
     - name: Make build folder
       run: mkdir -p build
       continue-on-error: true
@@ -184,9 +184,9 @@ jobs:
 
     - name: Run Tests
       if: ${{!inputs.is-prep-phase && !inputs.skip-test}}
-      env:
-        LD_LIBRARY_PATH: ${{env.LD_LIB_PATH}}
-      run: ${{env.TEST_EXE}} --log_format=JUNIT --log_sink=CI_test_result_${{inputs.flav}}.xml -p -l all || echo 'test execution returned error'
+      run: |
+        export LD_LIBRARY_PATH=${{env.LD_LIB_PATH}}
+        ${{env.TEST_EXE}} --log_format=JUNIT --log_sink=CI_test_result_${{inputs.flav}}.xml -p -l all || echo 'test execution returned error'
       timeout-minutes: ${{ inputs.nTestTimeoutMins}}
     
     - name: Upload Test Results
diff --git a/.github/workflows/build-test-lin-wsl.yml b/.github/workflows/build-test-lin-wsl.yml
--- a/.github/workflows/build-test-lin-wsl.yml
+++ b/.github/workflows/build-test-lin-wsl.yml
@@ -37,7 +37,7 @@ on:
         description: 'command to check if the builder is ready'
         default: 'cmake --version ; ninja --version ; gcc --version ; git --version; pwsh --version ||true '
         #pwsh is required on self hosted runners: see here: https://learn.microsoft.com/en-us/powershell/scripting/install/install-other-linux?view=powershell-7.2#installation-using-a-binary-archive-file     
-        required: false        
+        required: false
       bootstrap-cmd:
         type: string
         description: 'commands required to boot strap builder after code checkout'
@@ -198,12 +198,12 @@ jobs:
         ${{env.TEST_EXE}} --list_content > tests.txt
       timeout-minutes: 1
       shell: wsl-bash {0}
-      
+
     - name: Run Tests
       if: ${{!inputs.is-prep-phase && !inputs.skip-test}}
-      env:
-        LD_LIBRARY_PATH: ${{env.LD_LIB_PATH}}
-      run: ${{env.TEST_EXE}} --log_format=JUNIT --log_sink=CI_test_result_${{inputs.flav}}.xml -p -l all || echo 'test execution returned error'
+      run: |
+        export LD_LIBRARY_PATH=${{env.LD_LIB_PATH}}
+        ${{env.TEST_EXE}} --log_format=JUNIT --log_sink=CI_test_result_${{inputs.flav}}.xml -p -l all || echo 'test execution returned error'
       timeout-minutes: ${{ inputs.nTestTimeoutMins}}
       shell: wsl-bash {0}
     
diff --git a/.github/workflows/build-test-lin.yml b/.github/workflows/build-test-lin.yml
--- a/.github/workflows/build-test-lin.yml
+++ b/.github/workflows/build-test-lin.yml
@@ -37,7 +37,7 @@ on:
         description: 'command to check if the builder is ready'
         default: 'cmake --version ; ninja --version ; gcc --version ; git --version; pwsh --version ||true '
         #pwsh is required on self hosted runners: see here: https://learn.microsoft.com/en-us/powershell/scripting/install/install-other-linux?view=powershell-7.2#installation-using-a-binary-archive-file     
-        required: false        
+        required: false
       bootstrap-cmd:
         type: string
         description: 'commands required to boot strap builder after code checkout'
@@ -93,7 +93,7 @@ jobs:
       run: |
         (PATH=/usr/local/cuda/bin:$PATH && nvcc --version) || echo 'please install cuda and add /usr/local/cuda/bin into path'
         test -f /usr/local/cuda/include/cudnn.h || echo 'install cudnn as described in the readme.md'
-    
+
     - name: Cleanup workspace on self hosted runners
       if: inputs.is-selfhosted
       run: 'Remove-Item -Recurse -Force *'
@@ -169,7 +169,7 @@ jobs:
       if: ${{!inputs.is-prep-phase}}
       working-directory: ${{github.workspace}}/build
       run: cmake --build . --config ${{inputs.buildConf}} -j ${{ inputs.nProc }}
-    
+
     - name: List Test cases
       if: ${{!inputs.is-prep-phase}}
       run: |
@@ -180,9 +180,9 @@ jobs:
 
     - name: Run Tests
       if: ${{!inputs.is-prep-phase && !inputs.skip-test}}
-      env:
-        LD_LIBRARY_PATH: ${{env.LD_LIB_PATH}}
-      run: ${{env.TEST_EXE}} --log_format=JUNIT --log_sink=CI_test_result_${{inputs.flav}}.xml -p -l all || echo 'test execution returned error'
+      run: |
+        export LD_LIBRARY_PATH=${{env.LD_LIB_PATH}}
+        ${{env.TEST_EXE}} --log_format=JUNIT --log_sink=CI_test_result_${{inputs.flav}}.xml -p -l all || echo 'test execution returned error'
       timeout-minutes: ${{ inputs.nTestTimeoutMins}}
     
     - name: Upload Test Results
