some build tweaks

diff --git a/.github/workflows/CI.yml b/.github/workflows/CI.yml
--- a/.github/workflows/CI.yml
+++ b/.github/workflows/CI.yml
@@ -51,89 +51,112 @@ jobs:
       CACHE_REST_KEY: ${{ matrix.FLAV }}-build-cache-vcpkg
       TEST_RES_XML: CI_test_result_${{ matrix.FLAV }}.xml
       GST_BUILD_SHELL: ${{ matrix.SHELL }}
+      ISCUDA: ${{ contains(matrix.os, 'cuda') }}
+      TESTEXE: build/aprapipesut
 
     steps:
-    - name: Install build dependencies in cloud hosted env
-      run: ${{ matrix.BUILDER_PREP_CMD }}
+      - name: Install build dependencies in cloud hosted env
+        run: ${{ matrix.BUILDER_PREP_CMD }}
     
-    - name: Checkout code
-      uses: actions/checkout@v2
-      with: 
-        submodules: 'false'
-
-    - name: Checkout submodule
-      run: |
-        git submodule update --init --recursive 
-        git submodule status > submodule_ver.txt
+      - name: Checkout code
+        uses: actions/checkout@v3
+        with: 
+          submodules: 'false'
+          lfs: 'true'
+  
+          - name: Checkout submodule
+        run: |
+          git submodule update --init --recursive 
+          git submodule status > submodule_ver.txt
       
-    - name: Run VCPKG bootstrap
-      run: ${{ matrix.VCPKG_BOOTSTRAP_CMD }}
+      - name: Run VCPKG bootstrap
+        run: ${{ matrix.VCPKG_BOOTSTRAP_CMD }}
+  
+      - name: Cache dependencies for fast cloud build
+        id: cache-all
+        if: runner.arch != 'ARM64' # let's not cache from self hosted runner as it is caching anyways
+        uses: actions/cache@v3
+        with:
+            path: |
+              ${{ matrix.CACHE_PATH }}
+              thirdparty/gst-build/gst-build-1.16/outInstall/
+            key:  ${{ env.CACHE_REST_KEY }}-${{ hashFiles( matrix.VCPKG_FILE, matrix.GST_BUILD_SCRIPT, 'base/CMakeLists.txt', 'vcpkg/baseline.json', 'submodule_ver.txt') }}
+            restore-keys: ${{ env.CACHE_REST_KEY }}-
+  
+      - name: Build Gstreamer
+        if: ${{ runner.arch != 'ARM64' && steps.cache-all.outputs.cache-hit != 'true' }}
+        working-directory: ${{github.workspace}}/thirdparty
+          run: |
+            ls gst-build/gst-build-1.16/outInstall || true
+            ${{matrix.GST_BUILD_COMMAND}}
+  
+      - name: cache init
+          run: |
+            ls /github/home/.cache/vcpkg/archives || true
+            ls thirdparty/gst-build/gst-build-1.16/outInstall || true
+          continue-on-error: true
+           
+      - name: Make build folder
+        run: mkdir -p build
+        continue-on-error: true
+  
+      - name: Configure CMake Common
+        working-directory: ${{github.workspace}}/build
+        run: ${{ matrix.CMAKE-CONF }} -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DGHA=ON -DCMAKE_TOOLCHAIN_FILE=../vcpkg/scripts/buildsystems/vcpkg.cmake
+        continue-on-error: false
+        
+      - name: Build
+        working-directory: ${{github.workspace}}/build
+        run: cmake --build . --config ${{env.BUILD_TYPE}} -j ${{ matrix.NPROC }}
+        continue-on-error: false
+  
+      - name: Verify contents of our build
+          working-directory: ${{github.workspace}}/build/
+          run: dir *
+          continue-on-error: false
 
-    - name: Cache dependencies for fast cloud build
-      id: cache-all
-      if: runner.arch != 'ARM64' # let's not cache from self hosted runner as it is caching anyways
-      uses: actions/cache@v2
-      with:
+      - name: Override TESTEXE for windows
+        if: runner.os == 'Windows'
+        run: |
+          echo on ${{ runner.os }} change the test exe to ${{env.TESTEXE}}
+          echo "TESTEXE=${{env.TESTEXE}}" >> $GITHUB_ENV
+        env:
+          TESTEXE: build/${{env.BUILD_TYPE}}/aprapipesut.exe
+
+      - name: List test cases
+        env:
+          LD_LIBRARY_PATH: ${{github.workspace}}/thirdparty/gst-build/gst-build-1.16/outInstall/lib/x86_64-linux-gnu:$LD_LIBRARY_PATH
+        run: |
+          ${{ env.TESTEXE }} --list_content
+        continue-on-error: false
+     
+      - name: Test
+        if: ${{ env.ISCUDA != 'true'}}
+        env:
+          LD_LIBRARY_PATH: ${{github.workspace}}/thirdparty/gst-build/gst-build-1.16/outInstall/lib/x86_64-linux-gnu:$LD_LIBRARY_PATH
+        run: |
+          ${{ env.TESTEXE }} --log_level=all --log_format=JUNIT --log_sink=${{ env.TEST_RES_XML }}
+        timeout-minutes: 10
+        continue-on-error: false
+    
+      - name: Upload Test Results
+        if: always()
+        uses: actions/upload-artifact@v2
+        with:
+          name: TestResults_${{ matrix.FLAV }}
           path: |
-            ${{ matrix.CACHE_PATH }}
-            ${{github.workspace}}/thirdparty/gst-build/gst-build-1.16/outInstall/
-          key:  ${{ env.CACHE_REST_KEY }}-${{ hashFiles( matrix.VCPKG_FILE, matrix.GST_BUILD_SCRIPT, 'base/CMakeLists.txt', 'vcpkg/baseline.json', 'submodule_ver.txt') }}
-          restore-keys: ${{ env.CACHE_REST_KEY }}-
-
-    - name: Build Gstreamer
-      if: ${{ runner.arch != 'ARM64' && steps.cache-all.outputs.cache-hit != 'true' }}
-      working-directory: ${{github.workspace}}/thirdparty
-      run: ${{matrix.GST_BUILD_COMMAND}}
-          
-    - name: Make build folder
-      run: mkdir -p build
-      continue-on-error: true
-
-    - name: Configure CMake Common
-      working-directory: ${{github.workspace}}/build
-      run: ${{ matrix.CMAKE-CONF }} -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DGHA=ON -DCMAKE_TOOLCHAIN_FILE=${{github.workspace}}/vcpkg/scripts/buildsystems/vcpkg.cmake
-      continue-on-error: false
-      
-    - name: Build
-      working-directory: ${{github.workspace}}/build
-      run: cmake --build . --config ${{env.BUILD_TYPE}} -j ${{ matrix.NPROC }}
-      continue-on-error: false
-      
-    - name: Verify contents of Debug and Release in windows
-      if: runner.os == 'Windows'
-      working-directory: ${{github.workspace}}/build/
-      run: dir ${{env.BUILD_TYPE}}
-      continue-on-error: false
-    
-    - name: Test Linux
-      if: runner.os == 'Linux'
-      env:
-        LD_LIBRARY_PATH: ${{github.workspace}}/thirdparty/gst-build/gst-build-1.16/outInstall/lib/x86_64-linux-gnu:$LD_LIBRARY_PATH
-      run: build/aprapipesut --log_format=JUNIT --log_sink=${{ env.TEST_RES_XML }}
-
-    - name: Test Windows 
-      if: runner.os == 'Windows'
-      run: build/${{env.BUILD_TYPE}}/aprapipesut --log_format=JUNIT --log_sink=${{ env.TEST_RES_XML }}
-      continue-on-error: false
-    
-    - name: Upload Test Results
-      if: always()
-      uses: actions/upload-artifact@v2
-      with:
-        name: TestResults_${{ matrix.FLAV }}
-        path: |
-          ${{ env.TEST_RES_XML }}
-
-    - name: Upload build logs 
-      if:  ${{ failure() }} # only upload logs when we have a fialure above
-      uses: actions/upload-artifact@v2
-      with:
-        name: BuildLogs_${{ matrix.FLAV }}
-        path: |
-          ${{ github.workspace }}/build/**/*.log
-          ${{ github.workspace }}/build/**/*.txt
-          ${{ github.workspace }}/vcpkg/buildtrees/**/*.log
-          ${{ github.workspace }}/vcpkg/buildtrees/**/*.txt
+            ${{ env.TEST_RES_XML }}
+  
+      - name: Upload build logs 
+        if:  ${{ failure() }} # only upload logs when we have a failure above
+        uses: actions/upload-artifact@v2
+        with:
+          name: BuildLogs_${{ matrix.FLAV }}
+          path: |
+            ${{ github.workspace }}/build/**/*.log
+            ${{ github.workspace }}/build/**/*.txt
+            ${{ github.workspace }}/vcpkg/buildtrees/**/*.log
+            ${{ github.workspace }}/vcpkg/buildtrees/**/*.txt
   
   publish-test-results:
     name: "Publish Unit Tests Results"
